### ISSUE TITLE
Can you tell me how to transform the CTB to obtain dependency annotations?

### ISSUE THREAD

**Issue by sustcsonglin** [danifg/MultiPointer#1]
Specifically, how to transform LIU-GOLD-TEST.trees into dependency? Thank you very much

**Comment by danifg** [comment]
Augmented dependency treebanks necessary for training the Multitask Pointer Network on the CTB with Liu splits were sent to you privately.

**Comment by danifg** [comment]
Please find in attachment augmented dependency treebanks necessary for
training the Multitask Pointer Network on the CTB with Liu splits. Each
file includes in CoNLL format both the regular dependency treebank plus the
augmented variant that encodes constituents.

https://drive.google.com/file/d/1nP97MBs1ff3dWEsrfyLiw-FHwEQsLu3_/view?usp=sharing
https://drive.google.com/file/d/1rkKvzyRMBX_q8CNTBw8mobNynz61t2A4/view?usp=sharing
https://drive.google.com/file/d/1vJdphhhu4ip4pjTdns8MP6hCM_6XQP51/view?usp=sharing

**Comment by sustcsonglin** [comment]
Thank you very much

**Comment by sustcsonglin** [comment]
Can you tell me the details of transformation?  I use the rule from Table 8 (Zhang and Clark,
2008) as your paper mentioned and I use https://cl.lingfil.uu.se/~nivre/research/Penn2Malt.html to transform, but I got lots of different dependencies from your provided file.

**Comment by danifg** [comment]
I used the script https://github.com/andre-martins/TurboParser/tree/master/constituency_parser/scripts/converter.jar from the original work by Fernández-González and Martins (2015), which, given a dependency treebank, is able to automatically extract the head-rule set necessary for converting constituent data into dependencies. Then, by providing the dependency version defined by Zhang and Clark (2008), I managed to convert constituent splits described by Liu and Zhang (2017) into dependencies. Please note that it might be the case that Penn2Malt is not transforming some constituents the same way Zhang and Clark (2008) did in their original work.

**Comment by sustcsonglin** [comment]
Thank you for replying. This is helpful.
